### ISSUE TITLE
`-D`/`--define` ignored when not using repl

### ISSUE THREAD

**Issue by simao** [com-lihaoyi/mill#1439]
I don't know if this is expected behavior, but these options don't seem to work when not using a repl.

For example when using a main class like:

```scala
object Boot extends App {
  println("mytest: " + System.getProperty("mytest"))
}
```

```
❯ mill --no-server --define 'mytest=1' _.runMain eu._0io.Boot
mytest: null
```

Removing `--no-server` has no effect.

Using a repl works:

```
❯ mill --repl --define 'mytest=1' 
@ System.getProperty("mytest") 
res0: String = "1"
```

I am using mill 0.9.9.

**Comment by lefou** [comment]
This is actually by design. Also you're comparing apples and oranges here. With run, you're spawning a sub process whereas in the repl you're just calling a method in the mill process. If you going to call the run target in the repl, you should notice a different but consistent behavior.

If you want to pass arguments to a sub process (which run actually is), you need to override target `def forkArgs`. To set environment variables, override `def forkEnv`. Alternatively you can call target `runLocal`, which will _not_ spawn a new sub process but instead runs the main class in a isolated classloader. Then, your main app should see the system properties of the mill process.

**Comment by simao** [comment]
Thanks for your help.

Do I need anything extra to my classpath to use `testLocal` ? It cannot find some jars when testing if I just use `testLocal`. I was trying to use `--define` to override some properties in `application.conf` when running tests in CI, would like to avoid using `forkArgs` since that would break tests when running locally.

**Comment by lefou** [comment]
`testLocal` should work when `test` works. Please ask for help in the Discussions Forum (on Github) or the Gitter chat room with more info and detailed error messages.
