### ISSUE TITLE
JavaModule's `run` command arguments should be a `Task`

### ISSUE THREAD

**Issue by daddykotex** [com-lihaoyi/mill#1948]
Currently, we can't define a `def a: Task[String] = ???` and use that to call the `run` command from the `JavaModule`. See the minimal repo:

```scala
import mill._
import mill.scalalib._

object proj extends JavaModule {

/*

/private/tmp/def/build.sc:10: Target#apply() call cannot use `value args` defined within the T{...} block
    run(args)()
        ^
/private/tmp/def/build.sc:8: `T.sources` definitions must have 0 parameter lists
  def aCommand() = T.command {
      ^
Compilation Failed
*/
  def myArgs: T[String] = T { "arg" }

  def aCommand() = T.command {
    val args = myArgs()
    run(args)()
  }
}

```

As per a [conversation](https://gitter.im/lihaoyi/mill?at=62d01d0b9f73251a2c2e6d8b) on `gitter` with @lefou , a straightforward fix for that is to turn `def run(args: String*): Command[Unit]` into `def run(args: Task[Seq[String]]): Command[Unit]`

**Comment by lefou** [comment]
* See also https://github.com/com-lihaoyi/mill/discussions/1857

**Comment by lihaoyi** [comment]
I tried a prototype in https://github.com/com-lihaoyi/mill/pull/2452. Thinking about this, it appears there are a few options here:

1. `def run(args: Task[String]*)`: That should work already I think, but it limits the number way arguments can be passed to `run` since the number of arguments is fixed up front

2. `def run(args: Task[String*])` is not allowed by the Scala type system

3. `def run(args: Task[mainargs.Leftover[String]])` would require some patches to the `mainargs` library, because currently we hard-code support for `mainargs.Leftover[T]`. We'd need to un-hard-code it somehow to make the `Task[Leftover[String]]` param signature work, and then maybe provide an implicit constructor so people can pass in `run(Seq("foo"))` rather than `run(mainargs.Leftover(Seq("foo")))` at the callsite

4. Leave `def run(args: String*)` and just make it forward to an anonymous task `def run(args: Task[Seq[String]]) = T.task{...}`. This is probably the easiest thing to do to solve the immediate issue without major surgery, but doesn't generalize to other `T.command`s unless we repeat the boilerplate of `T.command`/`T.task` pairing for each one

It feels like either (3) or (4) are the best options here, depending on how much we want to generalize this v.s. how difficult it is to make the upstream `mainargs` changes necessary to support (3)

**Comment by lefou** [comment]
Beside what this means for the codebase, I think what we want is a `args: Task[Something]`. For different reasons.

* `Something` can be a `Seq[T]` to support variable count
* `Something` can be a case class or the like, which is easier to evolve in a binary compatible way

The `JavaModule.run` is a good example for a Seq-like parameter.

If we look at a more complex use case like `JavaModule.ivyDepsTree`, we see currently the following signature:

```scala
def ivyDepsTree(args: IvyDepsTreeArgs = IvyDepsTreeArgs()): Command[Unit]
```

with [IvyDepsTreeArgs](https://github.com/com-lihaoyi/mill/blob/main/scalalib/src/mill/scalalib/IvyDepsTreeArgs.scala), which is annotated with various `mainargs` annotation to be parseable.

**Comment by lihaoyi** [comment]
https://github.com/com-lihaoyi/mainargs/pull/62 has the mainargs necessary to make (3) work. It would be a binary compatibility breakage for Mainargs, but IMO it's probably worth doing sooner or later, as apart from supporting this feature it would also clean up a lot of cruft within the MainArgs codebase
