### ISSUE TITLE
Re-download JARs missing from Coursier cache

### ISSUE THREAD

**Issue by kierendavies** [com-lihaoyi/mill#2157]
If I clear my Coursier cache (`rm -r ~/.cache/coursier/`) then recompile a module, I get errors like
```
main.compile java.nio.file.NoSuchFileException: /home/kieren/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.2-RC1/scala3-compiler_3-3.2.2-RC1.jar
```

It would be nice if something detected the missing JARs and re-downloaded them.

It would also simplify some of my CI pipelines. Then I could propagate the entire `out` directory between jobs, and not worry about what's in the Coursier cache of the host running each job.

**Comment by lefou** [comment]
Thanks for reporting this. This is a tricky one. I think Mill's evaluator and cache manager isn't prepared for such scenario. I though about such cases in the past, and reasoned, that some kind of `--pedantic` mode might be nice, which always check for valid return `PathRef`s. But I never saw it reported, so forgot about it.

The thing is, that we currently don't detect in-valid cached targets based on the existence of their outcome. As none of the inputs has changed, we simple miss the opportunity to refresh the targets cached value. I think the initial assumption was, that things we control inside `T.dest` doesn't need to costly checked on each run. But cached dependencies resemble paths outside of `T.dest`, so we should provided an (optional) way to check whether the cached value is still valid, before using it as target value.

I have no clear picture yet of a nice API to do that. Some `T.checked` comes to mind. Or an additional `Result` type.

**Comment by lefou** [comment]
Here is a first draft, how we could implement it:

* Annotate the target or persistent target with `@validated`
* The `T` or `T.persistent` macro needs to detect the `@validate` and creates the internal `TargetImpl` with a new `validate = true` attribute
* The macro needs to make sure, the result type can be validated, e.g. `PathRef` or `Seq[PathRef]` (same as we support in `Source` and `Sources`).
* At evaluation time, when we found an already cached value, we need to check if the target has the `validate` attribute set to `true` and need to validate that the path references are valid (path needs to exists and the sig needs to be equal; best is to rely on the same logic as when creating a `PathRef`, so a new `def PathRef.validate(): Boolean` makes sense.)
* If the result is valid, continue with the cached value, otherwise, drop the cached value and re-evaluate the target.

This above algorithm should be implementable and work for the OP use case:

```scala
@validated def resolvedIvyDeps: Target[Seq[PathRef]] = T { ??? }
```

**Comment by lefou** [comment]
This is now fixed. You can set the `PathRef.revalidate` property to `Once` or `Always`, to trigger `sig`-checks. `CoursierModule.resolve` automatically sets it to `Once`. And `JavaModule.resolveIvyDeps` among other targets, immediately gain validated caches.
