### ISSUE TITLE
Integrate lefou/`millw` and `millw.bat` into Mill repository

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2161]
* https://github.com/lefou/millw

Goals:
* Keep all features of lefou/millw, except the `--mill-version` option
* Shell script needs to be POSIX shell compatible
* New Windows Batch script
* Remove parsing of (arbitrary) local `mill` script as fallback for an undefined Mill version

**Comment by JD557** [comment]
While I'm not qualified to help here, if the plan is to have a new windows .bat file, wouldn't it be better to just use a .ps1 file instead?

FWIW, Powershell comes installed in all windows versions since windows 7, and using that should avoid some of the legacy craft from batch.

**Comment by lefou** [comment]
I find it essential, that we support booting **all** older Mill versions, so that any old project can simply use the latest version of the script.

**Comment by lihaoyi** [comment]
@lefou I'd like to revisit this issue, in the run up to Mill 0.12/0.13

IIRC one point of contention was the globally installed `mill` executable parsing a project-specific `./mill` script to try and find the version to use. I used to think this was important, but I've changed my mine and would be willing to give that up now. Since we're now recommending usage being of `./mill` bootstrap scripts, the exact behavior when the global `mill` and local `./mill` diverges seems less important now than it used to be

Do you recall if there were any other points of contention? Or what other major ways in which `millw` diverges from the existing `mill` script?

**Comment by lefou** [comment]
While #4052 replaced the in-repo `mill` and `ci/mill.bat` scripts with the latest versions (`0.4.12 I guess) of `millw` and `millw.bat`, I think this is not enough to complete the move/archival of https://github.com/lefou/millw .

I think what we want is:
* import the `lefou/millw` project as a sub-project (do we need a re-licensing from Apache 2 to MIT?)
* treat scripts like source files, e.g. replace versions by placeholders
* Add a build steps to build final scripts where placeholders are replaced by the actual version
* Add some tests/integration tests to ensure these scripts still support older Mill versions
* Ensure we publish all scripts to the GitHub release page
  * `mill` - `sh`-compatible script
  * `mill.bat` - Windows Batch script
  * `mill.ps1` - Windows PowerShell scrip

**Comment by lihaoyi** [comment]
The licenses are compatible as long as we leave the attribution in place, which I have done. I have also implemented to the build steps to do the version mangling and publish the scripts.

I can add some basic integration smoketests tests

@lefou one question I have is 

> Windows PowerShell script

What's the purpose of having both `ps1` and `bat` scripts? For now I only used the `bat` script since I assume that works on all versions of windows

**Comment by lefou** [comment]
> What's the purpose of having both `ps1` and `bat` scripts? For now I only used the `bat` script since I assume that works on all versions of windows

I guess it's all about choice. `.bat` is the most compatible but less modern script. Some users prefer `.ps1`, esp. when they use PowerShell for everything else. There is no common shared syntax.

**Comment by lihaoyi** [comment]
In that case I think just sticking with `.bat` should be sufficient; it should run everywhere that `.ps1` runs, and can be called from both powershell or cmd.exe.

**Comment by JD557** [comment]
> In that case I think just sticking with `.bat` should be sufficient; it should run everywhere that `.ps1` runs, and can be called from both powershell or cmd.exe.

Is there any quick way to test both?

I would like to check that both .bat and .ps1 work in "complex" user directories (i.e. the ones that are converted to `SOMETHING~1` in batch).

That's the main reason I asked for a PowerShell version in a previous comment.

**Comment by lefou** [comment]
I'm not a Windows user, but I think the `ps1` script is the more modern way and the `bat` is more the compat thing. Since I'm the old guy with probably very old Windows habits, I use the `bat` script. But I think the `ps1` script was provided for a reason. We should not abandon it.
