### ISSUE TITLE
Vendor mill-mima, mill-vcs-version and mill-integration-test to make Mill bootstrapping self-contained

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#2466]
Currently, after releasing a new version of Mill, you cannot use it in ~any of the com.lihaoyi libraries until these dependencies are published as well. Essentially, the process of publishing com-lihaoyi/mill involves publishing 4 different repos owned by 3 different github users, in the right order, before anything useful can be done. Even re-bootstrapping Mill (https://github.com/com-lihaoyi/mill/pull/2463) is currently impossible without doing this

That is not acceptable to me. Not only does it make the whole process slow, it also makes it fragile (what if either one of @lolgab or @lefou goes on vacation?), and creates a ton of unnecessary manual work around CI and release. e.g. https://github.com/com-lihaoyi/mill/issues/2460 was not being surfaced/fixed early in CI by the person causing the breakage, and instead someone else had to do a retrospective investigation to debug the breakage. Rather than being a one-click "push a tag" release process, we have this multi-user dance of dependency-ordered publishing and ad-hoc-bug-fixing that easily takes days of manual work. 

We already have a story for `contrib/` plugins living in the Mill repo. The owners of `mill-mima`, `mill-vcs-version` and `mill-integration-test` all have push access to the Mill repo. We should in-source these three projects to the `contrib/` folder, to streamline the whole publishing and maintenance process. 

If folks need downstream plugins that depend on Mill but Mill itself doesn't use, or have Mill depend on upstream libraries that are standalone and do not depend on Mill, that stuff can remain external. But if there are circular dependencies where the library and Mill both depend on each other to bootstrap, those really should be co-located in the same repo.

**Comment by lefou** [comment]
I think lots of different aspect are a bit convoluted here, and I try to isolate some aspects as I seen them.

1. None of these external plugins is blocking Mill development in any way. Mill typically is using a stable version to build itself and all the used plugins are also released for this stable Mill version. Providing and using stable versions is IMHO a precondition for a rich ecosystem.

2. Mill uses the technique of bootstrapping (which typically involves the described dance) also for testing it's current build outcome on it's own code base. This is great for detecting issues but possible breakage is a given, even without the use of external plugins. If we would test our in-repository plugins in a more realistic setup (starting separate Mill processes vs. running some in-process test) we could probably detect more issue, but this is not guaranteed. Any API or behavior change we do needs some consideration in the bootstrap testing, hence we have setup a prepare-and-patch process which is cumbersome but otherwise works nicely. Of course, there is room for improvements.

3. As each other successful build tool, an stable and external plugin ecosystem is key! Contrib plugins are nice for when either the original author has no resources or interest in maintaining it externally or in case the plugins are only used by Mill itself. But contrib plugins have the downside, that they only work with the exact Mill version they are built and released with. Also maintenance above the minimal "keep-it-working" is unclear. To the contrary, external plugins can keep support for older Mill versions and even bring bug fixes and improvements to these versions, which is not possible with the current setup of contrib plugins in Mill. This is also the main reason I decided to spend this extra work to maintain most of my plugins externally.

4. In the context of Mill bootstrapping, we can discuss and we should, if it is acceptable to use external plugins at all. You said, you find it unacceptable. I see it differently. With a growing ecosystem, many more plugins will appear, and it would be a pity to not use them just because they are external. You can try to convince their authors to migrate them over to Mill. Maintaining a copy of them in Mill seems not to be the right approach to me.

5. You questioned the maintenance of external plugins. Now, I think, as always with open source, you can still take those plugins over once they are no longer maintained.

6. Richer testing of Mill: By building and integration testing one of my plugins I detected a regression (kind of, #2460). Of course, it would be nice to have seen it earlier. As a consequence, I think we should start to have something like a test suite for external projects with is often called a "community build". Even in Mill we have tests we don't run just because it would take too long. We also don't run all tests on all platforms. With such an extended test suite we could also include these tests and external projects and plugins to detect issues and regressions.

**Comment by lihaoyi** [comment]
Overall I don't have problems with using external code. What I do want to avoid though is hard circular dependencies with external code. 

To me, either of these is fine: 

1. We depend on external code, with the external code having no hard dependency on Mill. e.g. Mill depends on uPickle, but uPickle doesn't depend on a specific version of Mill and can use whatever.

2. External code depends on us, and we do not have a hard dependency on the external code. e.g. some external plugin X for specialized use case Y depend on Mill, but Mill does not depend on external plugin X

Circular dependencies like we have here forces synchronization points where we have to publish 3-4 repos simultaneously, as we are doing here. Regardless of how well-maintained external dependencies are, forcing this kind of synchronization point really defeats the purpose of having separate repos in the first place, since they can no longer evolve independently at their own pace and instead have to move together in lockstep.

There isn't any tradeoff here between ease of release and stability for the external plugin ecosystem. The tedium of publishing 3-4 repos to make a release isn't what keeps things stable, enforcing MiMa is, and that wouldn't change.

There are definitely things we can do with setting up community builds and what not, but for the current problem with two tiny plugins and ~600 lines of code that would be a huge overkill with massive complexity and increased maintenance burden. For now, the feasible option is In-sourcing the relevant plugins, and either fully migrating the maintenance of them in-tree or to fork off from the external version and allow them to diverge.

**Comment by lolgab** [comment]
> what if either one of @lolgab or @lefou goes on vacation?

This can easily be solved by giving access to key plugins to all Mill maintainers. I just invited @lihaoyi and @lefou as collaborators to mill-mima so you can merge PRs and push tags if I'm unavailable.

**Comment by lefou** [comment]
> Overall I don't have problems with using external code. What I do want to avoid though is hard circular dependencies with external code.
> 
> To me, either of these is fine:
> 
>     1. We depend on external code, with the external code having no hard dependency on Mill. e.g. Mill depends on uPickle, but uPickle doesn't depend on a specific version of Mill and can use whatever.
> 
>     2. External code depends on us, and we do not have a hard dependency on the external code. e.g. some external plugin X for specialized use case Y depend on Mill, but Mill does not depend on external plugin X
> 
> 
> Circular dependencies like we have here forces synchronization points where we have to publish 3-4 repos simultaneously, as we are doing here.

I think this circular dependency isn't as real as you describe it. Yes, it is there, as it is the core of the concept of bootstrapping. But actually, we _do not_ depend on a _new_ release of any external plugin to get the current development state of Mill out in the public. 

Mill is currently using stable Mill 0.10.12 to build itself and nothing forces us to wait for any external dependency to go on with development and releases. All dependencies published for Mill 0.10.0 onwards will do.

But, each project in the wild, that want's to use the latest (instable) release has naturally to wait for the availability of all used plugins. Mill is no distinction here. You try to use the latest Mill milestone release which comes without exactly no stability guarantees and expect to have the whole ecosystem at hand on the same day. If that is the requirement, than we can't use external plugins.

Do we need to use the latest release? No.

Do we want to use the latest release? Probably yes, as soon as possible. To dogfood it, to use newest features and to make dealing with our patch file more convenient. But otherwise, this dependency can be avoided or delayed. There is no real need to have it available in the exact moment a new Mill release comes out.

> Regardless of how well-maintained external dependencies are, forcing this kind of synchronization point really defeats the purpose of having separate repos in the first place, since they can no longer evolve independently at their own pace and instead have to move together in lockstep. And I consider re-bootstrapping the com.lihaoyi ecosystem to be a core part of evolving it; I want to use the code I write, in addition to publishing it for others!

If that means, you want it without delay, then we can't use external plugin. 

But we also use these plugins for a reason. For example, we need to maintain binary compatibility. We were ourselves very bad in maintaining it in the past, especially without any tooling. I for myself don't want to maintain even another tools myself just because I want to use it to provide a stable project, hence I use externally maintained plugins. There is for sure a trade-off, but I would rather wait a bit longer with switching Mill's build setup to the latest (unstable) Mill version than risking to produce unstable/incompatible releases or run into any other trap because of NIH.

> 
> There isn't any tradeoff here between ease of release and stability for the external plugin ecosystem. The tedium of publishing 3-4 repos to make a release isn't what keeps things stable, enforcing MiMa is, and that wouldn't change.

I don't see how those extra repos block a release.

> There are definitely things we can do with setting up community builds and what not, but for the current problem with two tiny plugins and ~600 lines of code that would be a huge overkill with massive complexity and increased maintenance burden. For now, the feasible option is In-sourcing the relevant plugins, and either fully migrating the maintenance of them in-tree or to fork off from the external version and allow them to diverge.

I have no issue with someone copying my plugin code into this repo, per se. But I have (in the current setup) zero options to keep a separate release lifecycle to provide fixes and improvements for user that don't want to keep their build tool on the cutting edge. I even think, most users will, once their setup has settled, stay on some stable tree, and almost all of my plugins support older Mill version and that style in general.

**Comment by lihaoyi** [comment]
> If that means, you want it without delay, then we can't use external plugin.

Yes, I think that's the difference here. I want to use the new release quickly, even if just a milestone. Throughout the com.lihaoyi ecosystem, and especially within Mill itself. For you it presumably doesn't matter as much, but for me it's important. Also having a relatively self-contained dependency tree probably matters more for me than for most people. As does zero-overhead releasing for unstable versions; there's a reason I had set up per-master-commit releases back then for Ammonite and (iirc) Mill

I think the path forward here is:

* I'll copy the two plugins into the Mill repo contrib/ folder, and can maintain them in-tree. They are relatively small codebases that change not super often, so I expect the maintenance burden will be minimal

* You can continue to maintain your plugin as a separate project, to better support projects on old Mill versions and for independent releases

* The compatibility story for the plugin ecosystem will renain unchanged. We will continue to use MiMa. You will continue re-publishing the external version of the plugin and catch any issues there

* I'll publish 0.11.0-M9 and move the com.lihaoyi projects to the contrib/ version of the plugins, to ensure a (relatively) self-contained dependency tree for those projects

If at some point we realize one of these approaches is redundant, we can kill it and just use the other. Or we the plugin codebase we need to use grows and maintaining two copies becomes unfeasible. Until then, we both have different priorities, and this will give us both what we want at the (relatively small) cost of vendoring small amount of slow-moving code.

**Comment by lefou** [comment]
Maybe we should explore our room for compromises a bit more:

* Find and differentiate hard requirement vs. nice-to-haves
* Explore tooling to use code of external plugin more easily
  * Use git submodule? I've had rather bad experience with it, but maybe I was doing it wrong?
  * Copy and patch the plugin code in-tree (for use from `build.sc`) and keep some tooling to refresh that copy when needed

**Comment by lefou** [comment]
Looks like we cross posted.

> * I'll publish 0.11.0-M9 and move the com.lihaoyi projects to the contrib/ version of the plugins, to ensure a (relatively) self-contained dependency tree for those projects

Let me be honest. For a long while (I'm too lazy to count, but it's at least a year) it felt to me that I'm the only maintainer for some of the com-lihaoyi repos. First and foremost Mill but also os-lib and some others. Some of your repos get only sparse issue/pr triage. Maintenance is hard, talking to users and being welcoming takes time. If you plan to make those repos more instable, tooling wise, I fear the extra burden. I really appreciate the drive you bring to projects, but all that code needs to be maintained, too. The interoperability story doesn't write itself alone, some thinking ahead is needed. Not all users write small script files that can easily upgrade. In reality, large transitive dependency trees are normal.

I definitely like to play with new feature, too. But making things unstable just because we can, isn't always the best idea. Users suffered a lot because of surprising incompatibilities is com-lihaoyi projects. There even exists some forks of them just to tackle more stability.

What is so urgent to move all other com-lihaoyi repo to a milestone version of Mill? We risk to loose some ecosystem support, not only the IDE, but also services like scala-steward, which currently provide great value in maintenance.

**Comment by lihaoyi** [comment]
> This can easily be solved by giving access to key plugins to all Mill maintainers. I just invited @lihaoyi and @lefou as collaborators to mill-mima so you can merge PRs and push tags if I'm unavailable.

That does solve the repo-owner-busy problem. We *could* move the repos under `con-lihaoyi` so people get access to it automatically - that's the point of the org after all! - but other problems remain: manual work to perform a release, needing to go back and forth between repos, etc.

We *could* write a community-build-like tool or a multi-repo-release-automation tool to try and remove that friction. That could automate away a lot of the friction of managing multiple repos. But setting up such a thing is itself a lot of work.

If the choice comes down to duplicating ~600 lines of code, or setting up and maintaining a community build and/or multi-repo-release-automation infrastructure, duplicating the code is probably an order of magnitude less work, complexity and maintenance burden

**Comment by lolgab** [comment]
> - Copy and patch the plugin code in-tree (for use from `build.sc`) and keep some tooling to refresh that copy when needed

About this approach, I maintain a Scala Native distribution of Cask in SNUnit. Recreating the module from the sources cloned with git is done in ~20 LOC of build.
Now that we have support for meta-builds, it's possible to do the same thing in the meta-build by fetching specific tags/commits of mill-mima and mill-vcs-version to be used in the Mill repository.

**Comment by lihaoyi** [comment]
> Let me be honest. For a long while (I'm too lazy to count, but it's at least a year) it felt to me that I'm the only maintainer for some of the com-lihaoyi repos. First and foremost Mill but also os-lib and some others. Some of your repos get only sparse issue/pr triage. Maintenance is hard, talking to users and being welcoming takes time. If you plan to make those repos more instable, tooling wise, I fear the extra burden. I really appreciate the drive you bring to projects, but all that code needs to be maintained, too. The interoperability story doesn't write itself alone, some thinking ahead is needed. Not all users write small script files that can easily upgrade. In reality, large transitive dependency trees are normal.

This is true, and I appreciate your work. I'd like to help more. One thing that would definitely help in that is reducing the feedback loop, because benefiting immediately from the improvements I make motivates me much more than writing improvements for a future me 6 months down the line.

I don't think it's urgency in changing these things, it's just that I'd like to make myself comfortable working with this code, just like you have made yourself comfortable working with it while you've been the primary maintainer and I've been inactive. To some extent, you just have to trust me, just like I trusted you to make widespread changes to the codebase as the maintainer even if I might not agree with every change.

And it seems there really isn't a huge tradeoff here anyway. Bootstrapping on unstable versions of Mill more frequently will just mean the bugs get surfaced and ironed out *before* the stable release, rather than *after*. That means we get bugs surfaced sooner so we can fix them, users get more stable stable releases, win-win.

**Comment by lihaoyi** [comment]
There are a number of ways we can do this:

1. Copy-paste the sources. Simplest technically, but causes duplication

2. Git Submodule of the downstream repo. I think we've all had bad experiences with Submodules, mostly stemming from the fact that their version varies separately from the parent repo, making managing the versions of parent and child repos tedious and error-prone

3. Download the downstream source bundle from Github and build it locally. This has the disadvantage of being at the mercy of the downstream repo, e.g. if it gets renamed or something this would break

4. Download the downstream source bundle from Maven Central and build it locally. This is probably the most robust way of getting sources, since short of a lawyer letter it's pretty hard to get something removed from Maven Central

One thing that would be difficult to sold is the mill-integration-test tests; these are part of the build.sc, not part of a Scala Module, which means they won't be part of the Maven Central source jars. In https://github.com/com-lihaoyi/mill/pull/2467, I ported them to Mill's internal example test framework, and IMO are a lot more readable than before (see below). 

1. Perhaps we can just skip these entirely, assuming the sources were tested in the downstream repo and not that much can go wrong from re-compiling them.

2. Or we can keep the example test suites I ported over, since it's not that much code anyway

```scala
// Before
        PathRef(testBase / "simple") -> Seq(
          TestInvocation.Targets(Seq("prepare")),
          TestInvocation.Targets(Seq("verify"), expectedExitCode = 1)
        ),

import mill._

import mill.scalalib._
import mill.scalalib.publish._
import $file.plugins
import com.github.lolgab.mill.mima._

trait Common extends ScalaModule with PublishModule {
  def scalaVersion = "2.13.4"
  def publishVersion = "0.0.1"
  def pomSettings =
    PomSettings("", organization = "org", "", Seq(), VersionControl(), Seq())
}
object prev extends Common
object curr extends Common with Mima {
  override def mimaPreviousArtifacts = T(Agg(ivy"org::prev:0.0.1"))
  override def mimaCheckDirection = CheckDirection.Backward
}

def prepare() = T.command {
  prev.publishLocal(sys.props("ivy.home") + "/local")()
}

def verify() = T.command {
  curr.mimaReportBinaryIssues()()
  ()
}
```
```scala
// After
import mill._

import mill.scalalib._
import mill.scalalib.publish._
import mill.mima._

trait Common extends ScalaModule with PublishModule {
  def scalaVersion = "2.13.4"
  def publishVersion = "0.0.1"
  def pomSettings =
    PomSettings("", organization = "org", "", Seq(), VersionControl(), Seq())
}

object prev extends Common
object curr extends Common with Mima {
  override def mimaPreviousArtifacts = T(Agg(ivy"org::prev:0.0.1"))
  override def mimaCheckDirection = CheckDirection.Backward
}


/** Usage
> ./mill prev.publishLocal
> ./mill curr.mimaReportBinaryIssues
...
error: Found 2 issue when checking against org:prev:0.0.1
error:  * static method hello()java.lang.String in class Main does not have a correspondent in current version
error:    filter with: ProblemFilter.exclude[DirectMissingMethodProblem]("Main.hello")
error:  * method hello()java.lang.String in object Main does not have a correspondent in current version
error:    filter with: ProblemFilter.exclude[DirectMissingMethodProblem]("Main.hello")
*/
```

**Comment by lefou** [comment]
@lihaoyi Once, I have more time, I'd like to review your rewrite of the integration tests. Maybe, we can somehow support them directly in mill-integrationtest, if they are able to test all the same situations. I always wanted those tests be more like a classic test suite, but the current status quo was good enough.

**Comment by lihaoyi** [comment]
@lefou one thing I'd like to get to is to publish our own internal test helpers publicly, and then put a "how to write/test/publish a Mill plugin" in the examples folder. 

One thing I would like to achieve is for the internal and external modules to use the same set of unit/integration/example tests, for internal plugins like Scalalib, contrib plugins, and external plugins. Then write a "how to write/test/publish a Mill plugin" to the examples suite so people can follow.

The code will probably need a considerable amount of cleanup to make it presentable enough to show other people. Definitely doable though

**Comment by lefou** [comment]
I added @lihaoyi and @lolgab as collaborators in [mill-vcs-version](https://github.com/lefou/mill-vcs-version) repository, so they can merge PRs and trigger (manual) CI runs.

In mill-vcs-version, every commit to the main repository and any tag gets automatically published. I also added a special `workflow_dispatch` configuration, with which you can start a manual CI run. In addition to the configured cross-targets, it fetches the latest Mill snapshot release and cross compiles against it. If that succeeds, it will publish with the full Mill version as platform version. With this setup, you can always produce a version of mill-vcs-version which is compatible to the latest Mill snapshot release. It will also suitable for re-bootstrapping the Mill build setup. Of course, this will also catch incompatibilities, so feel free to trigger that CI run after you published a Mill snapshot release (which is also published in the `workflow_dispatch` configuration).

**Comment by lihaoyi** [comment]
Ok, let's close this for now then now that the bus-factor issues around bootstrapping are resolved. I'm still not totally convinced by the bin-compat breakage workflow, but I'm willing to give it a shot to see how it goes for 0.11.0 and future. Can always re-open this in future if necessary
