### ISSUE TITLE
Documentaton links broken: Example Builds

### ISSUE THREAD

**Issue by hmf** [com-lihaoyi/mill#2659]
All links to example build scripts in [this section](http://mill-build.com/mill/Scala_Build_Examples.html#_example_builds) are broken.

**Comment by lefou** [comment]
This is due to the fact that you are looking at a snapshot build of the documentation, which assumes that snaphot is also published. But we currently do not publish all snapshots to avoid wasteful resource usage, but only some of them. While developing Mill 0.11 we changed our documentation generation process, and unfortunately, it  currently can't produce a version for older versions greater than 0.11.0-M8, especially not for 0.11.0 and 0.11.1 (which is currently the latest stable release). 

* See also https://github.com/com-lihaoyi/mill/issues/2455

**Comment by lefou** [comment]
Maybe, we can add the example zips to the documentation resources itself instead of linking to the release pages.

**Comment by hmf** [comment]
@lefou No problem. I am rereading the documentation and just wanted to warn about this in case you were not aware. No need to add the examples sources. I found these easily enough via Github's file search. 

BTW, in my opinion the latest documentation is very well laid out. Excellent work. Thank you to all who contributed.

**Comment by lefou** [comment]
I think the links to the example builds for real-work projects are indeed invalid. The new location is `example/thirdparty` and the set of project also differs.

**Comment by Huelse** [comment]
Hoping move the change log to a single file and add some of awesome demo codes may be helper?
