### ISSUE TITLE
How to see different version of API in Mill?

### ISSUE THREAD

**Issue by Nngxu** [com-lihaoyi/mill#2840]
I need to view the API for version 0.10.0 of the mill, but the API on the official web page is the latest version. How do I view the mill API for other versions？

**Comment by lefou** [comment]
We plan to provide versioned scaladoc on the documentation site (see https://github.com/com-lihaoyi/mill/issues/2455), but only for Mill since 0.11. For Mill older than 0.11, we don't have an aggregated/unified scaladoc. You can read them only per artifact, e.g. on javadoc.io (the `scalalib` scaladoc is at https://javadoc.io/doc/com.lihaoyi/mill-scalalib_2.13/0.10.0/mill/scalalib/index.html), or even easier: Just open a `build.sc` in the IDE, e.g. IntelliJ IDEA, and jump to the sources.

**Comment by lihaoyi** [comment]
@lefou I noticed that there seem to be old versions of the docs online, e.g. https://mill-build.com/mill/0.9.12/Intro_to_Mill.html

How is that the case? I thought we hadn't re-implemented multi version docs yet after 0.11.x

**Comment by lefou** [comment]
Before 0.11.0-M8, all documentation pages were static content, so it's easy to let Antora include them, and we do that. But in 0.11.0-M8, we started to generate pages on the fly. Antora has (to my knowledge) no option to run generation processes when checking out tags/branches/repos for inclusion, hence we can't include other newer versions. Instead, we need to persist these generated pages somewhere, e.g. by committing them to a doc branch per version. Then, we can configure Antora to use these branches.

**Comment by lihaoyi** [comment]
Oh ok. So this isn't a problem for 0.9 or 0.10, but will be a problem in future for 0.11 and beyond as the docs continue to evolve

**Comment by lihaoyi** [comment]
This has been fixed in https://github.com/com-lihaoyi/mill/pull/3325 and we now publish old versions of the docs
