### ISSUE TITLE
Scala 3 `build.sc`

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2969]
Mill is gaining adoption, but being a Scala 3 only build tool, would help it position itself as a next-generation build tool for Scala.

Sbt will be soon [running on Scala 3](https://github.com/sbt/sbt/pull/6746), so it would be nice if Mill did the same.

If we want to avoid breaking changes, we cross-compile Mill to Scala 3 and let users decide which version they want to use, either via the meta-build, a config file or a directive (like `//> using scala 3` from scala-cli).

**Comment by lihaoyi** [comment]
I think a breaking change for Scala 3 is fine IMO. Trying to keep things cross-building adds considerable internal complexity, and giving the user a choice adds considerable user-facing complexity. We should just make the jump

All of Mill's upstream Scala libraries are Scala 3 compatible, if I'm not mistaken. The normal code should be trivial to make cross-compatible (e.g. adding missing return type ascriptions for implicits), and the generated code should be similar (since it's just code). Most of the "heavy lifting" is already moved to `T.worker`s that live in separate classloaders

So the main work seems to be (a) porting the Applicative task macros to Scala 3 and (b) porting the line number fixer plugin to Scala 3. Neither of them seems terribly difficult, though we would need someone familiar with Scala 3 metaprogramming for (a) and Scala 3 internals for (b).

**Comment by kubukoz** [comment]
> All of Mill's upstream Scala libraries are Scala 3 compatible

Coursier will require a `_2.13` prefix afaik, but it should be fine... I think.

**Comment by lihaoyi** [comment]
Superseded by https://github.com/com-lihaoyi/mill/issues/3152
