### ISSUE TITLE
Command argument parsing behavior changed with Mill 0.11.7

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3004]
This is most likely caused by the mainargs version update from `0.5.4` to `0.6.1`

I have the following command, that stopped working as before and expected:

```scala
    def smokeTest(
        @mainargs.arg(doc = "Start the App inside a Xephyr server")
        xephyr: mainargs.Flag = mainargs.Flag(),
        @mainargs.arg(doc = "Start the App insie a Xvfb server")
        xvfb: mainargs.Flag = mainargs.Flag(),
        @mainargs.arg(doc = "The display server port to use")
        xport: String = ":90",
        @mainargs.arg(doc = "Arguments for the app launcher (e.g. `-console -consoleLog -noExit`)")
        args: mainargs.Leftover[String],
        @mainargs.arg(doc = "Timeout in seconds to cancel the test as failed")
        timeout: Int = 40
    ) = T.command { ... }
```

I typically start it as follows:

```sh
> mill my.app.smokeTest --xvfb --timeout 60 -consoleLog 
```

The `consoleLog` is supposed to be parsed into `args` parameter, since it is a `mainargs.Leftover[String]`.

Since the version bump to Mill `0.11.7`, it fails with the following error message:

```
> mill my.app.smokeTest --xvfb --timeout 60 -consoleLog 
...
Unknown argument: "-c"
Expected Signature: smokeTest
  --timeout <int>  Timeout in seconds to cancel the test as failed
  --xephyr         Start the App inside a Xephyr server
  --xport <str>    The display server port to use
  --xvfb           Start the App insie a Xvfb server
  args <str>...    Arguments for the app launcher (e.g. `-console -consoleLog -noExit`)

```

I also tried to force the parser to stop reading options with `--`, but it didn't work.

```
> mill my.app.smokeTest --xvfb --timeout 60 -- -consoleLog 
...
Unknown argument: "-c"
Expected Signature: smokeTest
  --timeout <int>  Timeout in seconds to cancel the test as failed
  --xephyr         Start the App inside a Xephyr server
  --xport <str>    The display server port to use
  --xvfb           Start the App insie a Xvfb server
  args <str>...    Arguments for the app launcher (e.g. `-console -consoleLog -noExit`)

```

**Comment by lihaoyi** [comment]
I think this is expected due to the syntax for `-consoleLog` now meaning `-c -o -n -s -o -l -e -L -o -g`

Maybe we can validate the entire `-combine` token first in MainArgs, and only use it as short token if everything matches, but otherwise throw the whole token to `Leftover`? That would probably be strictly better than the status quo of erroring out, which is probably unnecessarily pessimistic

**Comment by lefou** [comment]
I agree. It should only go in the report error mode, if there is no Leftover that can take the it.

**Comment by lefou** [comment]
Also, I think `mainargs` shouldn't even try to parse combined short options in cases like this, where I don't have a single short option defined.

**Comment by lihaoyi** [comment]
The over-eager erroring out is probably here:

https://github.com/com-lihaoyi/mainargs/pull/102/files#diff-43ca7abfb0abd6d68548dfffb2c189d5ff46628f78c39c61913200aff83165f2R103

Where we immediately return the error, rather than going through the normal `complete` codepath for finishing a parse that has a chance to handle `Leftover[T]` etc..

> Interestingly, I can work around with specifying --args before the args. Although, that means I can use Mill 0.11.7 for now, but I'm a bit surprised this works at all.

This is because we specifically look for a single-dash-followed-by-not-a-dash prefix before we start parsing combined short options https://github.com/com-lihaoyi/mainargs/pull/102/files#diff-43ca7abfb0abd6d68548dfffb2c189d5ff46628f78c39c61913200aff83165f2R101

> Also, I think mainargs shouldn't even try to parse combined short options in cases like this, where I don't have a single short option defined.

If we delegate to `Leftover` whenever parsing combined short options fails, it doesn't really matter whether it tries or not: it'll try parsing the first short option, fail, and then delegate the token and any subsequent tokes to `Leftover`. A bit of wasted work, not efficiency probably doesn't matter too much here

**Comment by lihaoyi** [comment]
https://github.com/com-lihaoyi/mainargs/pull/112 should fix this I think

**Comment by megri** [comment]
@lefou I think I'm hitting this error but I'm really confused as to what version of mill I'm actually running:

I am using [asdf](https://asdf-vm.com/) to manage versions in my project, and my project structure is as follows:

- root/.tool-versions - here mill is set to 0.11.7
- root/projects/app/.mill-version - sets mill to 0.11.7

Running `mill version` from the app directory reports version 0.11.7

When running `mill app.run` from directory root/projects/app I get the error
```
Unknown argument: "-D"
Expected Signature: run
  args <str>...
```

Either of these changes lets the app run:
1. Changing mill version in root/.tool-versions to 0.11.6: `mill version` still reports version 0.11.7;
2. Changing root/projects/app/.mill-version to 0.11.6: `mill version` now says 0.11.6.

So it seems like `mill version` simply outputs the version written in `.mill-version` but mill in fact uses mill defined in root/.tool-versions.
