### ISSUE TITLE
Add simpler `mill.scalalib.Dep` serialization for common cases

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3417]
`Dep` has a lot of fields, most of which are optional, but together it makes the serialized JSON impossible to skim. We should add some special casing to make the serialized form match the code string-literal form in the common case. e.g. instead of 

```json
$ cat /Users/lihaoyi/Github/mill/out/interation-tester-workdir/7385872308266233696/out/myplugin/test/testMill/ivyDeps.json
{
    "value": [
        {
            "dep": {
                "module": {
                    "organization": {
                        "value": "com.lihaoyi"
                    },
                    "name": {
                        "value": "mill-dist"
                    },
                    "attributes": {}
                },
                "version": "0.12.0-M0-42-581840-DIRTY17588c08",
                "configuration": {
                    "value": "default(compile)"
                },
                "minimizedExclusions": {
                    "data": "coursier.core.MinimizedExclusions.ExcludeNone"
                },
                "publication": {
                    "name": "",
                    "type": {
                        "value": ""
                    },
                    "ext": {
                        "value": ""
                    },
                    "classifier": {
                        "value": ""
                    }
                },
                "optional": false,
                "transitive": true
            },
            "cross": {
                "$type": "mill.scalalib.CrossVersion.Constant",
                "value": "",
                "platformed": false
            },
            "force": false
        }
    ],
    "valueHash": -1186909625,
    "inputsHash": -1440589820
}
```

We should serialize as 

```json
"com.lihaoyi:mill-dist:0.12.0-M0-42-581840-DIRTY17588c08"
```

We can preserve the existing verbose serialization for cases that fall outside the common case, but in most cases we should be able to get by with the short serialized form

**Comment by lefou** [comment]
I'd really love, if we could avoid to embed the `corsier.Dependency` class in our `Dep` class, once we can break compatibility. Beside the JSON representation which gets easier this way, we can fix other issues as well, e.g. the handling of excludes (since `exclusions` it's deprecated in `coursier.Dependency` in favor to `minimizedExcludes` which is a large data structure instead of high level meta data). It also brings us more close to an coursier-free API, where all coursier related stuff can live in workers.

Since I'm thinking of experimenting with alternative dependency resolvers, having a coursier free API in Mill would make it easier to drop-in alternatives, for whatever reasons.

Regarding the serialized format. Most typical dependency setups can be easily represented as appended key-value pairs. And some other settings from `coursier.Dependency` are even unsupported for Maven-dependencies and likely untested in Mill. It's better to model explicitly what we support and convert to `coursier` when needed.
