### ISSUE TITLE
Mill parallelism is not stable on windows

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3465]
Seems to constantly hit problems with Coursier. For now I turned off parallelism in our windows CI, but this results in windows CI being really slow, since we're not making use of the 4 cores the Github Actions runners have. Really the root cause should really be fixed

Examples

https://github.com/com-lihaoyi/mill/actions/runs/10709481836/job/29694216401
```
X mill.integration.MillPluginClasspathTest.exclusions 12487ms 
  utest.AssertionError: assert(res1.isSuccess)
  res1: mill.testkit.IntegrationTester.EvalResult = EvalResult(false,,1 targets failed
  resolvedIvyDeps java.io.FileNotFoundException: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\disneystreaming\smithy\smithytranslate-proto_2.13\0.5.3\smithytranslate-proto_2.13-0.5.3.pom (The process cannot access the file because it is being used by another process))
    utest.asserts.Asserts$.assertImpl(Asserts.scala:30)
    mill.integration.MillPluginClasspathTest$.$anonfun$tests$2(MillPluginClasspathTest.scala:36)
```

https://github.com/com-lihaoyi/mill/actions/runs/10729224027/job/29755559797?pr=3467

```
main.resolve.resolvedIvyDeps java.nio.file.AccessDeniedException: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\mainargs_2.13\0.7.4\.mainargs_2.13-0.7.4.jar__sha1.computed11218541499758406365.tmp -> C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\mainargs_2.13\0.7.4\.mainargs_2.13-0.7.4.jar__sha1.computed
Error: Process completed with exit code 1.
```

https://github.com/com-lihaoyi/mill/actions/runs/10729224027/job/29755559201?pr=3467

```
    com.fasterxml.jackson:jackson-base:2.11.4 
  	not found: C:\Users\runneradmin\.ivy2\local\com.fasterxml.jackson\jackson-base\2.11.4\ivys\ivy.xml
  	not found: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\.structure.lock (The process cannot access the file because it is being used by another process)
```

https://github.com/com-lihaoyi/mill/actions/runs/10729224027/job/29755559385?pr=3467

```
main.codesig.test.cases[callgraph-realistic-4-actors].resolvedIvyDeps java.nio.file.AccessDeniedException: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\wildfly\client\wildfly-client-config\1.0.1.Final\.wildfly-client-config-1.0.1.Final.jar__sha1.computed14587478017127854786.tmp -> C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\wildfly\client\wildfly-client-config\1.0.1.Final\.wildfly-client-config-1.0.1.Final.jar__sha1.computed
```

This PR should be sufficient to reproduce the problem https://github.com/com-lihaoyi/mill/pull/3467

**Comment by lefou** [comment]
It's not the first time we hit concurrency issues with coursier. Since there is no active development and not much guiding help from coursier side to fix it in coursier, we started to address some of these issues with retry handlers in Mill. Could be, we just need to add some more cases in our detection code? Not ideal, or course.

**Comment by lihaoyi** [comment]
We could and should, but since Alex is helping out with Mill starting next week im hoping he can help fix things upstream as well

**Comment by lihaoyi** [comment]
This should more or less be stabilized with the retry patterns https://github.com/com-lihaoyi/mill/blob/main/main/util/src/mill/util/CoursierSupport.scala#L20-L29, at least once we rebootstrap. But they could be fixed upstream as well

**Comment by alexarchambault** [comment]
Currently trying to reproduce these errors [here](https://github.com/alexarchambault/mill/tree/debug-coursier-windows)

**Comment by alexarchambault** [comment]
Managed to get the same error [here](https://github.com/alexarchambault/mill/actions/runs/10776911872/job/29885113694#step:10:10981) and [here](https://github.com/alexarchambault/mill/actions/runs/10777357800/job/29886576230#step:10:2672). The error seems to happen _somehow_ consistently, even though [that attempt](https://github.com/alexarchambault/mill/actions/runs/10776560962) succeeded (so that's 2 failures for 3 attempts here).

FTR, the error looks like this (always a `The process cannot access the file because it is being used by another process` with the `.structure.lock` file wrapped in a `not found`):
```text
 --------------------------------------------

#2     com.fasterxml:oss-parent:27 
#2   	not found: C:\Users\runneradmin\.ivy2\local\com.fasterxml\oss-parent\27\ivys\ivy.xml
#2   	not found: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\.structure.lock (The process cannot access the file because it is being used by another process)
#2   

#2   --------------------------------------------
```

Going to check if https://github.com/coursier/coursier/pull/3069 fixes it.

**Comment by alexarchambault** [comment]
Seems https://github.com/coursier/coursier/pull/3069 fixed the issue you were seeing here.

No issue in 5 attempts with it ([1](https://github.com/alexarchambault/mill/actions/runs/10779063052/job/29892099775), [2](https://github.com/alexarchambault/mill/actions/runs/10779277852/job/29892413629), [3](https://github.com/alexarchambault/mill/actions/runs/10779284754/job/29892434318), [4](https://github.com/alexarchambault/mill/actions/runs/10779676797/job/29894072879), [5](https://github.com/alexarchambault/mill/actions/runs/10779683922/job/29894101450), the last one being red because of some Scala Native issue rather than because of coursier).
