### ISSUE TITLE
Make it easier to use show/inspect/... from the REPL

### ISSUE THREAD

**Issue by smarter** [com-lihaoyi/mill#418]
Right now it's a bit awkward:
```scala
$ mill -i
@ inspect(replApplyHandler.evaluator, "main.compile")()
[1/1] inspect 
main.compile(ScalaModule.scala:125)
Inputs:
[...]
```
It'd be nicer if we could do:
```scala
@ inspect("main.compile")()
```
Or even:
```scala
@ inspect(main.compile)()
```

(It would also be nice to avoid the extra `()` but that's a separate issue)

The first should be achievable by having the evaluator implicitly available in scope and changing the signature of show/inspect/... to take the evaluator implicitly. @lihaoyi on Gitter said:
> Mill's routing macros do not support multiple arglists IIRC
> but they can be made to do so'
> the fork i use in Cask supports them

**Comment by lihaoyi** [comment]
This can probably be done most easily by changing the code wrapper template to wrap the expression in an additional e.g. `evalTask(...)` call, which would leave `T <!< Task`s alone and evaluate `T <:< Task`s the same way that `()` does so

**Comment by lihaoyi** [comment]
although it might still require patching ammonite's `Preprocessor.scala` to provide to appropriate hook for us to do this wrapping, since we may need to wrap at an expression level rather than at a block level so e.g. `main.compile; main.test` properly evaluates both tasks and stores their results in local bindings.

Apart from `inspect` and `show`, this would make working with the rest of Mill's tasks easier in the `mill -i` REPL as well

**Comment by lihaoyi** [comment]
This is now moot since https://github.com/com-lihaoyi/mill/pull/2377 removed the build REPL entirely due to lack of usage
