### ISSUE TITLE
Delegate commands to take parameters computed from other tasks

### ISSUE THREAD

**Issue by jodersky** [com-lihaoyi/mill#766]
It appears that it is not possible to call a command from another command with a parameter given as the result of another task. For instance:

```scala
object mod extends Module {

  def extra = T.input {
    "a"
  }

  def command1(arg: String) = T.command {
    println(arg)
  }

  def command2(arg: String) = T.command {
    command1(extra()) // replacing extra with arg or a literal works
  }

}
```

will give the following compile error:

```
build.sc: Target#apply() can only be used with a T{...} block
    command1(extra()) // replacing extra with arg or a literal works
                  ^
Compilation Failed
```

According to [this](https://gitter.im/lihaoyi/mill?at=5e31eeb76f9d3d3498ffd9e4) and [this](https://gitter.im/lihaoyi/mill?at=5d7a25047aa4717016c70882) conversation on Gitter, it appears that it is a current limitation of mill.

Since it isn't particularly easy to find old conversations on gitter, I'm reporting my findings in this issue, in the hopes that it may be easier to find in the future.

**Comment by jodersky** [comment]
As suggested by Haoyi:

> best workaround so far is to stuff all the "real logic" into a static helper function that someone else can then call without this issue

**Comment by lefou** [comment]
The typical pattern to apply non-static input to a target is to lift it to a task. So instead of accepting a `String` as parameter, you need to accept a `Task[String]`. Unfortunately, But Mill commands currently don't support Task as arguments, as there is no way to parse it from command line (yet). So the typical workaround is to create a `Task` with `T.task` and delegate to that task from the command.

Here is your modified example:

```scala
import mill._
import mill.define.Task

object mod extends Module {

  def extra = T.input {
    "a"
  }

  def command1Task(arg: Task[String]) = T.task {
    println(arg())
  }

  def command1(arg: String) = T.command {
    command1Task(T.task(arg))
  }

  def command2(arg: String) = T.command {
    command1Task(extra) 
  }

}
```

Maybe, we could come up with some automatic way to lift command parameter from `T` to `Task[T]`, so that the extra `def command1Task` is not needed.

**Comment by lefou** [comment]
FTR, https://discord.com/channels/632150470000902164/940067748103487558
