### ISSUE TITLE
Warn if directories are missing for task

### ISSUE THREAD

**Issue by kag0** [com-lihaoyi/mill#965]
I just proved myself a colossal idiot by refactoring my build file, but forgetting to re-arrange the folder structure as well. 
It would be helpful to beginners and fools (like myself) if there was a warning when you run a task for which there are no corresponding files or folders.
for example in the file structure
```
build.sc
projekt/
  test/
    src/
      mypkg/
        MyTests.scala 
```
and build file
```scala
import mill._, scalalib._
object project extends ScalaModule {
  object test extends Tests {
  ...
  }
  ...
}
```
we could output a warning like
> no directory 'project/test' found for module 'project.test' 

I would be happy to do some work on this if someone could give me a pointer on where to start or tips on how to go about it.

**Comment by lihaoyi** [comment]
This is a tricky problem, because I often have modules that have source or resource folders that intentionally empty. e.g. an "aggregate" module that just depends on everyone else to run assembly etc. without any of its own sources. Furthermore, modules have `src/`, `src-2/`, `src-2.x/`, and `src-2.x.y/` folders pre-defined most of which are also empty.

Also, I don't want warnings. Those are terminal noise that people tend to ignore. If we want people to opt-in explicitly to something, we can force them to define a flag

**Comment by lefou** [comment]
I could imagine a dedicated evaluator command like `show`, which reports all source targets that return an empty source set.

**Comment by kag0** [comment]
@lihaoyi 
> I often have modules that have source or resource folders that intentionally empty

what if it only triggered if the folder wasn't there at all, rather than was empty? 

>  I don't want warnings

what if we made this more specific to just tests, and made it an error rather than a warning? if there is a test module but no test folder, it seems reasonable to fail the test task rather than give the user (or CI) a false sense that all tests passed.

@lefou I think the tricky thing with a command is that the user has to already know what the issue is to make use of the command.

**Comment by lefou** [comment]
A warning might fix your use case, but might disturb many other users as well. I'm closing this issue. Feel free to open a new discussion to find a better solution.
